<!-- Entity Management -->
<li class="nav-item">
<a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
  <i class="bi bi-menu-button-wide"></i><span>Manage Entities</span><i class="bi bi-chevron-down ms-auto"></i>
</a>
<ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
	<li><a href="Book">Books</a></li>
</ul>
</li>	  
<!-- End Entity Management -->